os:
  - "osx"
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy-5.3.1"
install: pip install tox-travis coveralls
script: tox
after_success: coveralls
branches:
  only:
    - master
