os: osx
language: generic
env:
  - TOXENV=py27 PYENV_VERSION=2.7.13
  - TOXENV=py36 PYENV_VERSION=3.6.0
  - TOXENV=pypy PYENV_VERSION=pypy-5.6.0
before_install:
  - brew update
  - brew outdated pyenv || brew upgrade pyenv
  - export PYENV_ROOT="$(brew --prefix pyenv)"
  - export PATH="$PYENV_ROOT/shims:$PATH"
  - pyenv install -s $PYENV_VERSION
  - pyenv rehash && pyenv which python && which python
install: pip install -U tox coveralls
script: tox
after_success: coveralls
branches:
  only:
    - master
notifications:
  email: false
