os: osx
language: generic
env:
  - TOXENV=py27 PYENV_VERSION=2.7.15
  - TOXENV=py36 PYENV_VERSION=3.6.6
  - TOXENV=pypy PYENV_VERSION=pypy-5.7.1 NEED_OPENSSL=1
before_install:
  - brew update
  - brew outdated pyenv || brew upgrade pyenv
  - |
    if [ "x$NEED_OPENSSL" = "x1" ]; then
      brew install openssl@1.1;
      export LDFLAGS="-L$(brew --prefix openssl@1.1)/lib"
      export CFLAGS="-I$(brew --prefix openssl@1.1)/include"
    fi
  - export PYENV_ROOT="$(brew --prefix pyenv)"
  - export PATH="$PYENV_ROOT/shims:$PATH"
  - pyenv install -s $PYENV_VERSION
  - pyenv rehash && pyenv which python && pyenv which pip && which python && which pip
install:
  - curl https://bootstrap.pypa.io/get-pip.py | python  # See https://stackoverflow.com/a/49748494/718453
  - pip install -U pip setuptools wheel
  - pip install -U tox coveralls
script: tox
after_success: coveralls
branches:
  only:
    - master
notifications:
  email: false
